apiVersion: v1
kind: ConfigMap
metadata:
  name: 3xbat-config
  namespace: 3xbat
data:
  NODE_ENV: "production"
  FRONTEND_URL: "https://3xbat.com"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6380"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "betting_db"
  POSTGRES_USER: "postgres"
  # JWT_SECRET and POSTGRES_PASSWORD are in secrets.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: 3xbat
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
    upstream backend {
        least_conn;
        server backend-service:4000;
    }
        
        server {
            listen 80;
            server_name _;
            
            location /api/ {
                proxy_pass http://backend/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /ws {
                proxy_pass http://backend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
            }
            
            location / {
                proxy_pass http://client-panels-service:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
